-- MySQL Script generated by MySQL Workbench
-- 27 يول, 2015 EET 06:19:26 م
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema education
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema education
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `education` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `education` ;

-- -----------------------------------------------------
-- Table `education`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `education`.`user` ;

CREATE TABLE IF NOT EXISTS `education`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NULL,
  `email` VARCHAR(250) NULL,
  `password` VARCHAR(500) NULL,
  `salt` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `status` TINYINT NULL DEFAULT 1,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `education`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `education`.`student` ;

CREATE TABLE IF NOT EXISTS `education`.`student` (
  `idstudent` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(150) NULL COMMENT 'الاسم ',
  `first_name_en` VARCHAR(150) NULL,
  `father_name` VARCHAR(150) NULL,
  `father_name_en` VARCHAR(150) NULL,
  `grand_name` VARCHAR(150) NULL,
  `grand_name_en` VARCHAR(150) NULL,
  `last_name` VARCHAR(150) NULL,
  `last_name_en` VARCHAR(150) NULL,
  `mother_name` VARCHAR(45) NULL COMMENT 'اسم الام',
  `mother_name_en` VARCHAR(150) NULL,
  `birth_date` DATE NOT NULL COMMENT 'تاريخ الميلاد',
  `place_birth` INT NULL COMMENT 'مكان الميلاد',
  `nationality` INT NULL COMMENT 'الجنسية',
  `gender` TINYINT(1) NULL COMMENT 'الجنس\n1=ذكر\n2=انثى',
  `no_paper_family` INT NULL COMMENT 'رقم ورقة العائلة ',
  `no_reg_family` INT NULL COMMENT 'رقم قيد العائلة',
  `physical_address` TEXT NULL COMMENT 'عنوان الأقامة',
  `civil_reg` VARCHAR(100) NULL COMMENT 'السجل المدني ',
  `phone` VARCHAR(45) NULL COMMENT 'رقم الهاتف',
  `father_work_place` VARCHAR(150) NULL COMMENT 'مكان عمل الوالد',
  `last_cert` VARCHAR(100) NULL COMMENT 'اخر شهادة ',
  `cust_last_cert` VARCHAR(100) NULL COMMENT 'تخصيص اخر شهادة',
  `date_cert` DATE NULL COMMENT 'تاريخ الحصول علي الشهادة',
  `place_cert` VARCHAR(45) NULL COMMENT 'مكان الحصول عليها',
  `set_number` INT NULL COMMENT 'رقم الجلوس',
  `student_rate` FLOAT NULL COMMENT 'معدل الطالب',
  `nid` MEDIUMTEXT NULL COMMENT 'رقم الوطني',
  `status` INT NULL DEFAULT 1,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idstudent`),
  INDEX `fk_student_user1_idx` (`user_iduser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `education`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `education`.`department` ;

CREATE TABLE IF NOT EXISTS `education`.`department` (
  `iddepartment` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NULL COMMENT 'اسم القسم ',
  `name_en` VARCHAR(150) NULL,
  `status` TINYINT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`iddepartment`),
  INDEX `fk_department_user1_idx` (`user_iduser` ASC))
ENGINE = InnoDB
COMMENT = 'القسم ';


-- -----------------------------------------------------
-- Table `education`.`faculty_member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `education`.`faculty_member` ;

CREATE TABLE IF NOT EXISTS `education`.`faculty_member` (
  `idfaculty_member` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL COMMENT 'الاسم',
  `qualification` VARCHAR(45) NULL COMMENT 'المؤهل العلمي',
  `birth_date` DATE NULL COMMENT 'تاريخ الميلاد',
  `specialization` VARCHAR(45) NULL COMMENT 'التخصص',
  `gender` TINYINT(1) NULL COMMENT 'الجنس',
  `physical_address` VARCHAR(50) NULL COMMENT 'عنوان الأقامة',
  `phone` VARCHAR(50) NULL COMMENT 'رقم الهاتف',
  `place_birth` VARCHAR(50) NULL COMMENT 'مكان الميلاد',
  `department_iddepartment` INT NOT NULL,
  `nationality` INT NULL,
  `status` TINYINT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idfaculty_member`, `department_iddepartment`),
  INDEX `fk_faculty_member_department1_idx` (`department_iddepartment` ASC),
  INDEX `fk_faculty_member_user1_idx` (`user_iduser` ASC))
ENGINE = InnoDB
COMMENT = 'اعضاء هيئة التدريس';


-- -----------------------------------------------------
-- Table `education`.`subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `education`.`subject` ;

CREATE TABLE IF NOT EXISTS `education`.`subject` (
  `idsubject` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NULL COMMENT 'اسم المادة',
  `name_en` VARCHAR(150) NULL,
  `code` VARCHAR(45) NULL COMMENT 'رمز المادة',
  `no_th_unit` INT NULL COMMENT 'عدد الوحدات النظري ',
  `no_th_hour` INT NULL COMMENT 'عدد الساعات النظري ',
  `no_pr_unit` INT NULL COMMENT 'عدد الوحدات العملي ',
  `no_pr_hour` INT NULL COMMENT 'عدد الساعات العملي',
  `chapter_degree` FLOAT NULL COMMENT 'اعمال الفصل',
  `final_theor` FLOAT NULL COMMENT 'نهائي نظري ',
  `final_practical` FLOAT NULL COMMENT 'نهائي عملي',
  `sub_type` TINYINT(1) NULL DEFAULT 1 COMMENT 'نوع المادة عامة ام خاصة \n1 =خاص\n2 =عام',
  `department_iddepartment` INT NOT NULL,
  `status` TINYINT(1) NULL DEFAULT 1,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idsubject`),
  INDEX `fk_subject_department1_idx` (`department_iddepartment` ASC),
  INDEX `fk_subject_user1_idx` (`user_iduser` ASC))
ENGINE = InnoDB
COMMENT = 'المواد';


-- -----------------------------------------------------
-- Table `education`.`division`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `education`.`division` ;

CREATE TABLE IF NOT EXISTS `education`.`division` (
  `iddivision` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL COMMENT 'اسم الشعبة',
  `name_en` VARCHAR(150) NULL,
  `department_iddepartment` INT NOT NULL,
  `status` TINYINT(1) NULL DEFAULT 1,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`iddivision`),
  INDEX `fk_division_department1_idx` (`department_iddepartment` ASC),
  INDEX `fk_division_user1_idx` (`user_iduser` ASC))
ENGINE = InnoDB
COMMENT = 'الشعبة';


-- -----------------------------------------------------
-- Table `education`.`academic_transcript`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `education`.`academic_transcript` ;

CREATE TABLE IF NOT EXISTS `education`.`academic_transcript` (
  `idacademic_transcript` INT NOT NULL AUTO_INCREMENT,
  `result_case` TINYINT(1) NULL COMMENT 'حالة النتيجة',
  `chapter_degree` FLOAT ZEROFILL NULL COMMENT 'اعمال الفصل',
  `sum_dagree` FLOAT NOT NULL COMMENT 'مجموع الدرجات',
  `final_exam` FLOAT NULL COMMENT 'الامتحان النهائي',
  `course_idsubject` INT NOT NULL,
  `student_idstudent` INT NOT NULL,
  `division_iddivision` INT NOT NULL,
  `department_iddepartment` INT NOT NULL,
  `status` TINYINT(1) NULL DEFAULT 1,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL,
  `user_iduser` INT NOT NULL,
  `sub_group_idsub_group` INT NOT NULL,
  PRIMARY KEY (`idacademic_transcript`, `sum_dagree`, `sub_group_idsub_group`),
  UNIQUE INDEX `idacademy-std-Pstage_UNIQUE` (`idacademic_transcript` ASC),
  INDEX `fk_academy-std-Pstage_course1_idx` (`course_idsubject` ASC),
  INDEX `fk_academy-std-Pstage_student1_idx` (`student_idstudent` ASC),
  INDEX `fk_academy-std-Pstage_department1_idx` (`department_iddepartment` ASC),
  INDEX `fk_academy-std-Pstage_division1_idx` (`division_iddivision` ASC),
  INDEX `fk_academic_transcript_user1_idx` (`user_iduser` ASC),
  INDEX `fk_academic_transcript_sub_group1_idx` (`sub_group_idsub_group` ASC))
ENGINE = InnoDB
COMMENT = 'بيانات الطلبة الاكاديمية';


-- -----------------------------------------------------
-- Table `education`.`semester`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `education`.`semester` ;

CREATE TABLE IF NOT EXISTS `education`.`semester` (
  `idsemester` INT NOT NULL AUTO_INCREMENT,
  `sem_type` TINYINT(1) NULL COMMENT '1=ربيعي\n2=خريفي\n3=صيفي',
  `year` VARCHAR(45) NULL COMMENT 'السنة',
  `current` TINYINT(1) NULL DEFAULT 1,
  `starting_date` DATE NULL,
  `ending_date` DATE NULL,
  `status` TINYINT(1) NULL DEFAULT 1,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`idsemester`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `education`.`sub_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `education`.`sub_group` ;

CREATE TABLE IF NOT EXISTS `education`.`sub_group` (
  `idsub_group` INT NOT NULL AUTO_INCREMENT,
  `subject_idsubject` INT NOT NULL,
  `semester_idsemester` INT NOT NULL,
  `sub_group_name` TINYINT(1) NULL DEFAULT 1,
  `sub_groupcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idsub_group`, `subject_idsubject`, `semester_idsemester`),
  INDEX `fk_subject_has_semester_semester1_idx` (`semester_idsemester` ASC),
  INDEX `fk_subject_has_semester_subject1_idx` (`subject_idsubject` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `education`.`academic_transcript`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `education`.`academic_transcript` ;

CREATE TABLE IF NOT EXISTS `education`.`academic_transcript` (
  `idacademic_transcript` INT NOT NULL AUTO_INCREMENT,
  `result_case` TINYINT(1) NULL COMMENT 'حالة النتيجة',
  `chapter_degree` FLOAT ZEROFILL NULL COMMENT 'اعمال الفصل',
  `sum_dagree` FLOAT NOT NULL COMMENT 'مجموع الدرجات',
  `final_exam` FLOAT NULL COMMENT 'الامتحان النهائي',
  `course_idsubject` INT NOT NULL,
  `student_idstudent` INT NOT NULL,
  `division_iddivision` INT NOT NULL,
  `department_iddepartment` INT NOT NULL,
  `status` TINYINT(1) NULL DEFAULT 1,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL,
  `user_iduser` INT NOT NULL,
  `sub_group_idsub_group` INT NOT NULL,
  PRIMARY KEY (`idacademic_transcript`, `sum_dagree`, `sub_group_idsub_group`),
  UNIQUE INDEX `idacademy-std-Pstage_UNIQUE` (`idacademic_transcript` ASC),
  INDEX `fk_academy-std-Pstage_course1_idx` (`course_idsubject` ASC),
  INDEX `fk_academy-std-Pstage_student1_idx` (`student_idstudent` ASC),
  INDEX `fk_academy-std-Pstage_department1_idx` (`department_iddepartment` ASC),
  INDEX `fk_academy-std-Pstage_division1_idx` (`division_iddivision` ASC),
  INDEX `fk_academic_transcript_user1_idx` (`user_iduser` ASC),
  INDEX `fk_academic_transcript_sub_group1_idx` (`sub_group_idsub_group` ASC))
ENGINE = InnoDB
COMMENT = 'بيانات الطلبة الاكاديمية';



-- -----------------------------------------------------
-- Table `education`.`subject_has_subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `education`.`subject_has_subject` ;

CREATE TABLE IF NOT EXISTS `education`.`subject_has_subject` (
  `subject_idsubject` INT NOT NULL,
  `subject_idsubject1` INT NOT NULL,
  `status` TINYINT(1) NULL DEFAULT 1,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`subject_idsubject`, `subject_idsubject1`),
  INDEX `fk_subject_has_subject_subject2_idx` (`subject_idsubject1` ASC),
  INDEX `fk_subject_has_subject_subject1_idx` (`subject_idsubject` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `education`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `education`.`location` ;

CREATE TABLE IF NOT EXISTS `education`.`location` (
  `idlocation` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NULL,
  `quantity` INT NULL,
  `status` TINYINT NULL DEFAULT 1,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idlocation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `education`.`timeline`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `education`.`timeline` ;

CREATE TABLE IF NOT EXISTS `education`.`timeline` (
  `idtimeline` INT NOT NULL AUTO_INCREMENT,
  `semester_idsemester` INT NOT NULL,
  `sub_group_idsub_group` INT NOT NULL,
  `subject_idsubject` INT NOT NULL,
  `starting_time` TIME NULL,
  `day` TINYINT(1) NULL COMMENT '1= سبت	\n2= احد	\n3=اثنين\nوهكذا',
  `ending_time` TIME NULL,
  `location_idlocation` INT NOT NULL,
  PRIMARY KEY (`idtimeline`, `semester_idsemester`, `sub_group_idsub_group`, `subject_idsubject`),
  INDEX `fk_timeline_semester1_idx` (`semester_idsemester` ASC),
  INDEX `fk_timeline_sub_group1_idx` (`sub_group_idsub_group` ASC, `subject_idsubject` ASC),
  INDEX `fk_timeline_location1_idx` (`location_idlocation` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;